root: .
output_dir: ctllm_output
token_limit: 8000
project_type: Go Library
ignore_patterns:
- .DS_Store
- LICENSE
- README.md
- CHANGELOG.md
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- SECURITY.md
- .git/
- .github/
- .vscode/
- .idea/
- .gitignore
- '*.log'
- '*.out'
- '*.tmp'
- '*.pid'
- '*.lock'
- '*.pid'
- '*.pid'
- '*.pid'
- vendor/
- bin/
- '*.exe'
- '*.dll'
- '*.so'
- '*.dylib'
- .DS_Store
